
package com.zking.sell.biz;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IProductBizService", targetNamespace = "http://biz.sell.zking.com/", wsdlLocation = "http://localhost:8080/sell/services/product?wsdl")
public class IProductBizService
    extends Service
{

    private final static URL IPRODUCTBIZSERVICE_WSDL_LOCATION;
    private final static WebServiceException IPRODUCTBIZSERVICE_EXCEPTION;
    private final static QName IPRODUCTBIZSERVICE_QNAME = new QName("http://biz.sell.zking.com/", "IProductBizService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/sell/services/product?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        IPRODUCTBIZSERVICE_WSDL_LOCATION = url;
        IPRODUCTBIZSERVICE_EXCEPTION = e;
    }

    public IProductBizService() {
        super(__getWsdlLocation(), IPRODUCTBIZSERVICE_QNAME);
    }

    public IProductBizService(WebServiceFeature... features) {
        super(__getWsdlLocation(), IPRODUCTBIZSERVICE_QNAME, features);
    }

    public IProductBizService(URL wsdlLocation) {
        super(wsdlLocation, IPRODUCTBIZSERVICE_QNAME);
    }

    public IProductBizService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, IPRODUCTBIZSERVICE_QNAME, features);
    }

    public IProductBizService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IProductBizService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IProductBiz
     */
    @WebEndpoint(name = "IProductBizPort")
    public IProductBiz getIProductBizPort() {
        return super.getPort(new QName("http://biz.sell.zking.com/", "IProductBizPort"), IProductBiz.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IProductBiz
     */
    @WebEndpoint(name = "IProductBizPort")
    public IProductBiz getIProductBizPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://biz.sell.zking.com/", "IProductBizPort"), IProductBiz.class, features);
    }

    private static URL __getWsdlLocation() {
        if (IPRODUCTBIZSERVICE_EXCEPTION!= null) {
            throw IPRODUCTBIZSERVICE_EXCEPTION;
        }
        return IPRODUCTBIZSERVICE_WSDL_LOCATION;
    }

}
