
package com.zking.sell.biz;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IStorageBiz", targetNamespace = "http://biz.sell.zking.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IStorageBiz {


    /**
     * 
     * @param storage
     * @return
     *     returns java.util.List<com.zking.sell.biz.Storage>
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "list", targetNamespace = "http://biz.sell.zking.com/", className = "com.zking.sell.biz.List")
    @ResponseWrapper(localName = "listResponse", targetNamespace = "http://biz.sell.zking.com/", className = "com.zking.sell.biz.ListResponse")
    public List<Storage> list(
        @WebParam(name = "storage", targetNamespace = "")
        Storage storage);

}
