
package com.zking.sell.biz;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IStorageBizService", targetNamespace = "http://biz.sell.zking.com/", wsdlLocation = "http://localhost:8080/sell/services/storage?wsdl")
public class IStorageBizService
    extends Service
{

    private final static URL ISTORAGEBIZSERVICE_WSDL_LOCATION;
    private final static WebServiceException ISTORAGEBIZSERVICE_EXCEPTION;
    private final static QName ISTORAGEBIZSERVICE_QNAME = new QName("http://biz.sell.zking.com/", "IStorageBizService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/sell/services/storage?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ISTORAGEBIZSERVICE_WSDL_LOCATION = url;
        ISTORAGEBIZSERVICE_EXCEPTION = e;
    }

    public IStorageBizService() {
        super(__getWsdlLocation(), ISTORAGEBIZSERVICE_QNAME);
    }

    public IStorageBizService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ISTORAGEBIZSERVICE_QNAME, features);
    }

    public IStorageBizService(URL wsdlLocation) {
        super(wsdlLocation, ISTORAGEBIZSERVICE_QNAME);
    }

    public IStorageBizService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ISTORAGEBIZSERVICE_QNAME, features);
    }

    public IStorageBizService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IStorageBizService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IStorageBiz
     */
    @WebEndpoint(name = "IStorageBizPort")
    public IStorageBiz getIStorageBizPort() {
        return super.getPort(new QName("http://biz.sell.zking.com/", "IStorageBizPort"), IStorageBiz.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IStorageBiz
     */
    @WebEndpoint(name = "IStorageBizPort")
    public IStorageBiz getIStorageBizPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://biz.sell.zking.com/", "IStorageBizPort"), IStorageBiz.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ISTORAGEBIZSERVICE_EXCEPTION!= null) {
            throw ISTORAGEBIZSERVICE_EXCEPTION;
        }
        return ISTORAGEBIZSERVICE_WSDL_LOCATION;
    }

}
